<?php if ( ! defined( 'ABSPATH' ) ) { exit; } $type = is_array( $article_type ) ? $article_type : array(); $id = absint( $type['id'] ?? 0 ); $categories = get_categories( array( 'hide_empty' => false ) ); ?>
<div class="wrap wpai-admin">
<h1><?php echo esc_html( $id ? __( 'Modifica Tipologia articolo', 'wp-ai-publisher' ) : __( 'Aggiungi Tipologia articolo', 'wp-ai-publisher' ) ); ?></h1>
<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
<input type="hidden" name="action" value="wpai_publisher_save_article_type" /><input type="hidden" name="id" value="<?php echo esc_attr( (string) $id ); ?>" /><?php wp_nonce_field( 'wpai_publisher_save_article_type_' . $id ); ?>
<table class="form-table"><tbody>
<?php foreach ( array( 'name'=>'Nome', 'tone'=>'Tono', 'length'=>'Lunghezza', 'search_intent'=>'Intento ricerca', 'reader_level'=>'Livello lettore' ) as $key=>$label ) : ?><tr><th><label for="<?php echo esc_attr($key); ?>"><?php echo esc_html__($label,'wp-ai-publisher'); ?></label></th><td><input class="regular-text" id="<?php echo esc_attr($key); ?>" name="<?php echo esc_attr($key); ?>" value="<?php echo esc_attr( (string) ( $type[$key] ?? '' ) ); ?>" <?php echo 'name'===$key?'required':''; ?> /></td></tr><?php endforeach; ?>
<?php foreach ( array( 'description'=>'Descrizione', 'prompt'=>'Prompt', 'structure'=>'Struttura', 'required_sections'=>'Sezioni obbligatorie', 'forbidden_patterns'=>'Pattern vietati', 'preferred_tags'=>'Tag preferiti', 'quality_checklist'=>'Checklist qualità' ) as $key=>$label ) : ?><tr><th><label for="<?php echo esc_attr($key); ?>"><?php echo esc_html__($label,'wp-ai-publisher'); ?></label></th><td><textarea class="large-text" rows="<?php echo 'prompt'===$key?8:4; ?>" id="<?php echo esc_attr($key); ?>" name="<?php echo esc_attr($key); ?>"><?php echo esc_textarea( is_array( $type[$key] ?? null ) ? implode( "\n", $type[$key] ) : (string) ( $type[$key] ?? '' ) ); ?></textarea></td></tr><?php endforeach; ?>
<tr><th><?php esc_html_e( 'Categorie consentite', 'wp-ai-publisher' ); ?></th><td><?php foreach ( $categories as $cat ) : ?><label style="display:block"><input type="checkbox" name="allowed_category_ids[]" value="<?php echo esc_attr( (string) $cat->term_id ); ?>" <?php checked( in_array( (int) $cat->term_id, (array) ( $type['allowed_category_ids'] ?? array() ), true ) ); ?> /> <?php echo esc_html( $cat->name ); ?></label><?php endforeach; ?><p class="description"><?php esc_html_e( 'Se vuoto, la bozza non riceverà categorie suggerite dall’AI.', 'wp-ai-publisher' ); ?></p></td></tr>
<tr><th><?php esc_html_e( 'Attiva', 'wp-ai-publisher' ); ?></th><td><label><input type="checkbox" name="is_active" value="1" <?php checked( (bool) ( $type['is_active'] ?? true ) ); ?> /> <?php esc_html_e( 'Disponibile nel workflow Idee contenuto', 'wp-ai-publisher' ); ?></label></td></tr>
</tbody></table><?php submit_button( __( 'Salva tipologia', 'wp-ai-publisher' ) ); ?>
</form></div>
