<?php
/**
 * Facebook Page auto-publishing on article publish.
 *
 * @package WPAIPublisher
 */

namespace WPAIPublisher;

use WP_Post;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Shares a post to a Facebook Page when it is published.
 *
 * A per-post checkbox ("Condividi su Facebook") opts a post in. On the
 * draft->publish transition the share is deferred to WP-Cron (non-blocking,
 * with an anti-duplicate lock) and the resulting Facebook post ID/URL is stored
 * on the post. Designed so an Instagram channel can be added later alongside.
 */
class Facebook_Integration {

	const CRON_HOOK     = 'wpai_publisher_facebook_publish';
	const META_SHARE    = '_wpai_fb_share';
	const META_DONE     = '_wpai_fb_shared_at';
	const META_POST_ID  = '_wpai_fb_post_id';
	const META_ERROR    = '_wpai_fb_error';
	const GRAPH_VERSION = 'v19.0';

	/**
	 * Logger service.
	 *
	 * @var Logger
	 */
	private $logger;

	/**
	 * AI provider adapter (for optional AI captions).
	 *
	 * @var AI_Provider_Adapter
	 */
	private $ai_provider;

	/**
	 * Constructor.
	 *
	 * @param Logger              $logger Logger service.
	 * @param AI_Provider_Adapter $ai_provider AI provider adapter.
	 */
	public function __construct( Logger $logger, AI_Provider_Adapter $ai_provider ) {
		$this->logger      = $logger;
		$this->ai_provider = $ai_provider;
	}

	/**
	 * Register hooks.
	 *
	 * @return void
	 */
	public function register() {
		add_action( 'transition_post_status', array( $this, 'on_transition_post_status' ), 10, 3 );
		add_action( self::CRON_HOOK, array( $this, 'publish_to_facebook' ), 10, 1 );
		add_action( 'add_meta_boxes', array( $this, 'register_meta_box' ) );
		add_action( 'save_post', array( $this, 'save_meta_box' ), 10, 2 );
		add_action( 'admin_post_wpai_publisher_facebook_test', array( $this, 'handle_test_connection' ) );
	}

	/**
	 * Whether the integration is enabled and minimally configured.
	 *
	 * @return bool
	 */
	private function is_configured() {
		$settings = wpai_publisher_get_settings();
		return ! empty( $settings['facebook_enabled'] )
			&& '' !== trim( (string) ( $settings['facebook_page_id'] ?? '' ) )
			&& '' !== wpai_publisher_get_facebook_access_token();
	}

	/**
	 * Default value for the per-post "share" checkbox.
	 *
	 * @param int $post_id Post ID.
	 * @return bool
	 */
	private function default_share_for_post( $post_id ) {
		$settings = wpai_publisher_get_settings();
		if ( empty( $settings['facebook_default_share'] ) ) {
			return false;
		}
		// Pre-check only for posts generated by the plugin.
		return '1' === (string) get_post_meta( $post_id, '_wpai_publisher_generated', true );
	}

	/**
	 * Register the editor meta box.
	 *
	 * @return void
	 */
	public function register_meta_box() {
		add_meta_box(
			'wpai-facebook-share',
			__( 'WP AI Publisher — Facebook', 'wp-ai-publisher' ),
			array( $this, 'render_meta_box' ),
			'post',
			'side',
			'default'
		);
	}

	/**
	 * Render the meta box.
	 *
	 * @param WP_Post $post Post.
	 * @return void
	 */
	public function render_meta_box( $post ) {
		$post_id = (int) $post->ID;
		$stored  = get_post_meta( $post_id, self::META_SHARE, true );
		$checked = ( '' === $stored ) ? $this->default_share_for_post( $post_id ) : ( '1' === (string) $stored );
		wp_nonce_field( 'wpai_publisher_fb_meta', 'wpai_publisher_fb_meta_nonce' );

		echo '<label><input type="checkbox" name="wpai_fb_share" value="1" ' . checked( $checked, true, false ) . '> ' . esc_html__( 'Condividi su Facebook alla pubblicazione', 'wp-ai-publisher' ) . '</label>';

		if ( ! $this->is_configured() ) {
			echo '<p class="description">' . esc_html__( 'Configura la Pagina e il token in Impostazioni → Facebook per abilitare la condivisione.', 'wp-ai-publisher' ) . '</p>';
		}

		$done    = (string) get_post_meta( $post_id, self::META_DONE, true );
		$fb_id   = (string) get_post_meta( $post_id, self::META_POST_ID, true );
		$fb_err  = (string) get_post_meta( $post_id, self::META_ERROR, true );
		if ( '' !== $fb_id ) {
			$url = 'https://www.facebook.com/' . rawurlencode( $fb_id );
			echo '<p class="description">' . esc_html__( 'Pubblicato su Facebook:', 'wp-ai-publisher' ) . ' <a href="' . esc_url( $url ) . '" target="_blank" rel="noopener">' . esc_html( $fb_id ) . '</a>';
			if ( '' !== $done ) {
				echo ' <span>(' . esc_html( $done ) . ')</span>';
			}
			echo '</p>';
		} elseif ( '' !== $fb_err ) {
			echo '<p class="description" style="color:#b32d2e;">' . esc_html__( 'Ultimo errore:', 'wp-ai-publisher' ) . ' ' . esc_html( $fb_err ) . '</p>';
		}
	}

	/**
	 * Persist the meta box checkbox.
	 *
	 * @param int     $post_id Post ID.
	 * @param WP_Post $post Post.
	 * @return void
	 */
	public function save_meta_box( $post_id, $post ) {
		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
			return;
		}
		if ( ! isset( $_POST['wpai_publisher_fb_meta_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['wpai_publisher_fb_meta_nonce'] ) ), 'wpai_publisher_fb_meta' ) ) {
			return;
		}
		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}
		if ( $post instanceof WP_Post && 'post' !== $post->post_type ) {
			return;
		}
		update_post_meta( $post_id, self::META_SHARE, isset( $_POST['wpai_fb_share'] ) ? '1' : '0' );
	}

	/**
	 * Schedule the share on publish.
	 *
	 * @param string  $new_status New status.
	 * @param string  $old_status Old status.
	 * @param WP_Post $post Post.
	 * @return void
	 */
	public function on_transition_post_status( $new_status, $old_status, $post ) {
		if ( ! ( $post instanceof WP_Post ) || 'post' !== $post->post_type ) {
			return;
		}
		if ( 'publish' !== $new_status || 'publish' === $old_status ) {
			return;
		}
		if ( ! $this->is_configured() ) {
			return;
		}
		if ( '1' !== (string) get_post_meta( $post->ID, self::META_SHARE, true ) ) {
			return;
		}
		// Anti-duplicate: skip when already shared.
		if ( '' !== (string) get_post_meta( $post->ID, self::META_POST_ID, true ) ) {
			return;
		}

		if ( ! wp_next_scheduled( self::CRON_HOOK, array( (int) $post->ID ) ) ) {
			wp_schedule_single_event( time() + 5, self::CRON_HOOK, array( (int) $post->ID ) );
		}
		if ( function_exists( 'spawn_cron' ) ) {
			spawn_cron();
		}
	}

	/**
	 * Cron callback: publish the post to the Facebook Page.
	 *
	 * @param int $post_id Post ID.
	 * @return void
	 */
	public function publish_to_facebook( $post_id ) {
		$post_id = absint( $post_id );
		$post    = $post_id > 0 ? get_post( $post_id ) : null;
		if ( ! ( $post instanceof WP_Post ) || 'publish' !== $post->post_status ) {
			return;
		}
		if ( ! $this->is_configured() ) {
			return;
		}
		// Anti-duplicate lock.
		if ( '' !== (string) get_post_meta( $post_id, self::META_POST_ID, true ) ) {
			return;
		}

		$settings = wpai_publisher_get_settings();
		$page_id  = trim( (string) $settings['facebook_page_id'] );
		$token    = wpai_publisher_get_facebook_access_token();
		$link     = get_permalink( $post_id );
		$message  = $this->build_message( $post, (array) $settings );

		$share_mode = (string) ( $settings['facebook_share_mode'] ?? 'link' );
		$image_url  = '';
		if ( has_post_thumbnail( $post_id ) ) {
			$image_url = (string) wp_get_attachment_image_url( get_post_thumbnail_id( $post_id ), 'large' );
		}

		if ( 'photo' === $share_mode && '' !== $image_url ) {
			$endpoint = $page_id . '/photos';
			$body     = array( 'url' => $image_url, 'caption' => $message . "\n" . $link, 'access_token' => $token );
		} else {
			$endpoint = $page_id . '/feed';
			$body     = array( 'message' => $message, 'link' => $link, 'access_token' => $token );
		}

		$response = wp_remote_post(
			'https://graph.facebook.com/' . self::GRAPH_VERSION . '/' . $endpoint,
			array( 'timeout' => 30, 'body' => $body )
		);

		if ( is_wp_error( $response ) ) {
			$this->record_error( $post_id, $response->get_error_message() );
			return;
		}
		$code = (int) wp_remote_retrieve_response_code( $response );
		$data = json_decode( (string) wp_remote_retrieve_body( $response ), true );
		if ( $code < 200 || $code >= 300 || ! is_array( $data ) ) {
			$detail = is_array( $data ) && isset( $data['error']['message'] ) ? (string) $data['error']['message'] : ( 'HTTP ' . $code );
			$this->record_error( $post_id, $detail );
			return;
		}

		$fb_id = (string) ( $data['post_id'] ?? $data['id'] ?? '' );
		if ( '' === $fb_id ) {
			$this->record_error( $post_id, __( 'Risposta Facebook senza ID post.', 'wp-ai-publisher' ) );
			return;
		}

		update_post_meta( $post_id, self::META_POST_ID, $fb_id );
		update_post_meta( $post_id, self::META_DONE, current_time( 'mysql' ) );
		delete_post_meta( $post_id, self::META_ERROR );
		$this->logger->info( __( 'Articolo condiviso su Facebook.', 'wp-ai-publisher' ), array( 'source' => 'facebook', 'event' => 'shared', 'post_id' => $post_id, 'fb_post_id' => $fb_id ) );
	}

	/**
	 * Store and log a share error.
	 *
	 * @param int    $post_id Post ID.
	 * @param string $message Error message.
	 * @return void
	 */
	private function record_error( $post_id, $message ) {
		update_post_meta( $post_id, self::META_ERROR, sanitize_text_field( (string) $message ) );
		$this->logger->warning( __( 'Condivisione Facebook non riuscita.', 'wp-ai-publisher' ), array( 'source' => 'facebook', 'event' => 'share_failed', 'post_id' => absint( $post_id ), 'message' => (string) $message ) );
	}

	/**
	 * Build the message text for the Facebook post.
	 *
	 * @param WP_Post             $post Post.
	 * @param array<string,mixed> $settings Settings.
	 * @return string
	 */
	private function build_message( $post, $settings ) {
		$post_id     = (int) $post->ID;
		$title       = get_the_title( $post_id );
		$meta_title  = (string) get_post_meta( $post_id, '_aioseo_title', true );
		$meta_desc   = (string) get_post_meta( $post_id, '_aioseo_description', true );
		$excerpt     = has_excerpt( $post_id ) ? get_the_excerpt( $post_id ) : '';
		$link        = (string) get_permalink( $post_id );
		$hashtags    = $this->build_hashtags( $post_id );

		// Optional AI caption.
		if ( ! empty( $settings['facebook_use_ai_caption'] ) && method_exists( $this->ai_provider, 'generate_short_text' ) ) {
			$caption = $this->generate_ai_caption( $title, $meta_desc ?: $excerpt, $hashtags, $link );
			if ( '' !== $caption ) {
				return $caption;
			}
		}

		$template = (string) ( $settings['facebook_message_template'] ?? '' );
		if ( '' === trim( $template ) ) {
			$template = "{title}\n\n{meta_description}\n\n{hashtags}\n👉 {link}";
		}
		$replacements = array(
			'{title}'            => $title,
			'{meta_title}'       => '' !== $meta_title ? $meta_title : $title,
			'{meta_description}' => '' !== $meta_desc ? $meta_desc : $excerpt,
			'{excerpt}'          => $excerpt,
			'{link}'             => $link,
			'{hashtags}'         => $hashtags,
		);
		$message = strtr( $template, $replacements );

		// Collapse leftover blank lines from empty placeholders.
		$message = preg_replace( "/\n{3,}/", "\n\n", (string) $message );
		return trim( (string) $message );
	}

	/**
	 * Build a hashtag string from the post tags.
	 *
	 * @param int $post_id Post ID.
	 * @return string
	 */
	private function build_hashtags( $post_id ) {
		$tags = get_the_tags( $post_id );
		if ( ! is_array( $tags ) ) {
			return '';
		}
		$out = array();
		foreach ( array_slice( $tags, 0, 5 ) as $tag ) {
			$slug = preg_replace( '/[^\p{L}\p{N}]/u', '', (string) $tag->name );
			if ( '' !== $slug ) {
				$out[] = '#' . $slug;
			}
		}
		return implode( ' ', $out );
	}

	/**
	 * Generate a social caption via the AI (best effort).
	 *
	 * @param string $title Title.
	 * @param string $description Description.
	 * @param string $hashtags Hashtags.
	 * @param string $link Link.
	 * @return string Caption or empty string on failure.
	 */
	private function generate_ai_caption( $title, $description, $hashtags, $link ) {
		$prompt = sprintf(
			"Scrivi un breve testo per un post Facebook che promuove questo articolo. Tono coinvolgente ma professionale, 1-3 frasi, in italiano, senza emoji eccessive. Includi un invito alla lettura. NON inserire il link (verrà aggiunto a parte). Titolo: %s. Descrizione: %s. Hashtag suggeriti: %s.",
			$title,
			$description,
			$hashtags
		);
		$result = $this->ai_provider->generate_short_text( $prompt, __( 'Sei un social media manager. Rispondi solo con il testo del post.', 'wp-ai-publisher' ) );
		if ( is_wp_error( $result ) ) {
			$this->logger->warning( __( 'Caption AI per Facebook non generata; uso il template.', 'wp-ai-publisher' ), array( 'source' => 'facebook', 'event' => 'ai_caption_failed', 'message' => $result->get_error_message() ) );
			return '';
		}
		$caption = trim( (string) $result );
		if ( '' !== $hashtags && false === strpos( $caption, '#' ) ) {
			$caption .= "\n\n" . $hashtags;
		}
		$caption .= "\n👉 " . $link;
		return $caption;
	}

	/**
	 * Admin action: verify the Facebook Page connection.
	 *
	 * @return void
	 */
	public function handle_test_connection() {
		if ( ! current_user_can( wpai_publisher_capability() ) ) {
			wp_die( esc_html__( 'Permessi insufficienti.', 'wp-ai-publisher' ) );
		}
		check_admin_referer( 'wpai_publisher_facebook_test' );

		$settings = wpai_publisher_get_settings();
		$page_id  = trim( (string) ( $settings['facebook_page_id'] ?? '' ) );
		$token    = wpai_publisher_get_facebook_access_token();

		if ( '' === $page_id || '' === $token ) {
			$this->finish_test( __( 'Configura l’ID Pagina e il token (costante WPAIP_FACEBOOK_ACCESS_TOKEN).', 'wp-ai-publisher' ), false );
		}

		$response = wp_remote_get(
			add_query_arg(
				array( 'fields' => 'name,fan_count', 'access_token' => $token ),
				'https://graph.facebook.com/' . self::GRAPH_VERSION . '/' . rawurlencode( $page_id )
			),
			array( 'timeout' => 20 )
		);
		if ( is_wp_error( $response ) ) {
			$this->finish_test( $response->get_error_message(), false );
		}
		$data = json_decode( (string) wp_remote_retrieve_body( $response ), true );
		if ( ! is_array( $data ) || isset( $data['error'] ) ) {
			$detail = is_array( $data ) && isset( $data['error']['message'] ) ? (string) $data['error']['message'] : __( 'risposta non valida', 'wp-ai-publisher' );
			$this->finish_test( sprintf( __( 'Connessione fallita: %s', 'wp-ai-publisher' ), $detail ), false );
		}
		$name = (string) ( $data['name'] ?? '' );
		$this->finish_test( sprintf( __( '✅ Connessa alla Pagina: %s', 'wp-ai-publisher' ), '' !== $name ? $name : $page_id ), true );
	}

	/**
	 * Store the test result and redirect to settings.
	 *
	 * @param string $message Message.
	 * @param bool   $ok Success.
	 * @return void
	 */
	private function finish_test( $message, $ok ) {
		set_transient(
			'wpai_publisher_facebook_notice_' . get_current_user_id(),
			array( 'ok' => (bool) $ok, 'message' => sanitize_text_field( (string) $message ) ),
			60
		);
		wp_safe_redirect( add_query_arg( 'wpai_notice', 'facebook_test', admin_url( 'admin.php?page=wp-ai-publisher-settings' ) ) );
		exit;
	}
}
